### ISSUE TITLE
Can login with wrong credential

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/remote-server#1085]
Been relayed with:
https://github.com/openmsupply/openmsupply-client/issues/1197
https://github.com/openmsupply/remote-server/issues/1061

Access thingy, so raising a new one

Think this time is nailed.
What is happening is: Even if the user tries to login to a wrong password i.e with previous password, It allows to login.

### Steps to reproduce:

- Setup Central, remote and the Front end
- After the setup is completed, It should work normally
- Once it is on workable state
- From Central server, change that User password, but make sure you know your last password
- Once the Password is changed
- From the Frontend, Type that user last password
- This user will be authenticated fine from Remote server and takes to the Front end Dashboard page
- Doing restart of the remote server still does not make any difference

But....

- Once from the frontend, If logged in with the new password which is just changed
- And tries to re-login with the Previous Password, It does not validate which is correct But redoing `Steps to reproduce` will again be a problem

**Comment by clemens-msupply** [comment]
I suspect that in `service/src/login.rs` in `do_login` the central server login failure doesn't get interpreted as a LoginFailure error...

**Comment by andreievg** [comment]
what should happen to user credentials once user tries to login to central but has entered invalid password (but it's valid password in remote data) ?

**Comment by andreievg** [comment]
do we have a flag 'outdated password' or something like that ?

**Comment by clemens-msupply** [comment]
Good question. So we would have to remove the local user/permissions if:
1) Central server available
2) AND user login failed with "wrong password"
2) AND entered password is the correct current remote server password

**Comment by andreievg** [comment]
> Good question. So we would have to remove the local user/permissions if:
> 1) Central server available
> 2) AND user login failed with "wrong password"
> 2) AND entered password is the correct current remote server password

I think the condition is very good, `but` we shouldn't remove user or permissions (removing user would mean a placeholder user will be now shown in UI). Can we just add a flag on a user ? Full name for the flag would be `last_login_to_central_with_local_password_failed`, but of-course it can be `allow_offline_login` = false/true (with comment in db why it's there)

**Comment by clemens-msupply** [comment]
you mean if a user is still logged into another client and does a mutation and then the placeholder is used because the user has been deleted during a parallel login? good point!

I can think of two options:
1) Invalidate existing sessions for this user (by removing all tokens from the TokenBucket) so that the user is forced to log in using the new correct password.
2) Or as you said flag the user so that the user need to login with the new password.

Option 1) would logout the user from all sessions and I am not sure if its good or bad. On the pro side it enforces the re-login earlier which increases that change the central server is online during the login. Moreover, if the old password got compromised all sessions are terminated... However, existing client side changes might get lost when changing the password.
