### ISSUE TITLE
Programs: define and create patient table

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#1092]
Initially only the following columns are required:
- patient id
- first name
- last name
- date of birth
- gender

**Comment by Chris-Petty** [comment]
Seems cool! How does this overlap with the name table? Would first/last be denormalised, stored on both tables?

Rather, is the use case for this table to allow looking up patients with it instead of searching the `name` table?

If for searching, important fields I'd say to add:

- `code`, short identifier for humans
- `address`, often used to narrow down the right patient (though, possible we should have multiple addresses but making an `address` table if we haven't made one yet. In that case it'd be the "primary" address displayed in a list I reckon). 

For what it's worth, I believe Tamanu manages to keep the full list of patients available on remote sites is by having condensed patient identifying records synced everywhere. With that you could have high availability of syncing patients without database size getting out of control. Could then request for related data to the patient and visible if you want related data synced regularly.

**Comment by clemens-msupply** [comment]
The current idea is to have dispensing somewhat decoupled from the patient programs, e.g. the full patient record could have sensible data and data that is not really needed for dispensing. We could have a condensed de-normalised name entry for every patient which containing information only needed for dispensing. However, having another look at the `name` table I think we might be able to use it to store/query generic patient data for programs and have a full medical record in a document. Open for suggestions!

**Comment by Chris-Petty** [comment]
Ah right, so seeing the `patient` record as potentially having sensitive info while `name` remains the search and identifying source. That probably more consistent with current schema so all good, probably don't need to add code/address.

**Comment by clemens-msupply** [comment]
Closing because currently using name table.

Open question though: a patient might be at multiple stores with different patient information, e.g. not yet merged patients. Ok to clone names with for different stores?
