### ISSUE TITLE
Reduce PgPool cloning

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/remote-server#217]
At present, all repositories own their own clone of a `PgPool` instance:

```
pub struct SomeRepository {
  pool: sqlx::PgPool,
}
```

These are all just references to the same underlying `ConnectionPool`, so in practice probably not that bad, but it feels like unnecessary memory allocations for all the duplicate `Pool` cruft.

In the past, I tried to keep ownership of `pool` in the caller (`main.rs`) and just have the repos all borrow it, but I was missing some knowledge at the time and couldn't get it working. Looking back, I think the `pool` needed to be explicitly `static` (which I think should be fine, as the database should live the entire program runtime).

@chris-morgan Any thoughts?

**Comment by chris-morgan** [comment]
The repos largely won’t be able to *borrow* it, because they more or less need to be `'static`.

You *can* get around that by boxing a value and leaking it (so that it will never be freed), but that’s not a pattern that I would encourage.

Besides which, since `PgPool` is wrapping an `Arc`, working with references would be negligibly *less* efficient—double indirection rather than single. Cloning an `Arc` is just bumping a reference count, so here that’d just be a negligible extra startup cost; subsequently accessing an `Arc` has the same cost as accessing a reference.

The primary opposing proposal to promiscuous pool propagation is the pure programming paradigm of deliberate database delivery, where you store the DB somewhere and pass it in as the first argument every time you want to get something from the database. The main reason why this might be desirable (apart from the inherent reasoning benefits of purity) is if you need to work against multiple databases, including if the database configuration can change mid-process—but if that were the case, then you would also have the option of wrapping the pool(s) in a type that allows you to manage multiple pools, and get access to the one you want right now.

A hybrid approach would be to have repositories not contain the database, and have accessing the repository hand you a `struct RepositoryWithDatabase<T: Repository>(&PgPool, T)` (could be `PgPool` too, doesn’t much matter), and implement the methods on `RepositoryWithDatabase<T>` rather than `T`. Making repositories inert like this is very probably unnecessary overhead (in code and at runtime) for no meaningful benefit, but could possibly be useful if repositories can be created dynamically or if database configuration changes.

Conclusion: I’m not fond of storing the pool everywhere, but I’ve come to the conclusion it’s probably the pragmatic approach.

**Comment by wlthomson** [comment]
> The primary opposing proposal to promiscuous pool propagation is the pure programming paradigm of deliberate database delivery, where you store the DB somewhere and pass it in as the first argument every time you want to get something from the database. 

AFAICS, injecting the database as a parameter wouldn't be too hard to do, but I think it would make the mocking a bit more complicated? 

Perhaps best approach for now is to leave as is?

**Comment by wlthomson** [comment]
Closing.
