### ISSUE TITLE
Doc action trigger

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#231]
* Doc action to run only when PR merged to master with changes in docs folder (or possible schema docs folder, see below)
* Probably don't need the secret in the action (it's public repo), hold on does that mean anyone can put anything in our gh-pages page ? (or is protected branch ?)
* If we go along with https://github.com/openmsupply/remote-server/issues/230, would be good to have an action to also update gh-pages branches with lates schema docs (with similar mechanism as above)

**Comment by wlthomson** [comment]
> Probably don't need the secret in the action (it's public repo)...

The token isn't directly exposed, just the environment variable for the token (this is required for the action to push to the branch). The contents of the secret itself are still private (I believe it's a PAT generated by @craigdrown, so only he actually knows what it is).

> ... hold on does that mean anyone can put anything in our gh-pages page ? (or is protected branch ?)

I created a git branch rule so that the `gh-pages` branch can't be directly committed to 👍 .

> Doc action to run only when PR merged to master with changes in docs folder (or possible schema docs folder, see below)

Sounds good to me!

> If we go along with Schema Documentation with SchemaSpy #230, would be good to have an action to also update gh-pages branches with lates schema docs (with similar mechanism as above)

Will leave this one for #230.
