### ISSUE TITLE
Support multiple DBs at runtime

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#258]
In the best case we have an ORM that supports both DBs. However, this is probably not realistic, e.g. we plan to store and query JSON data. For this reason we most likely end up with:
- common ORM code for 'simple' queries
- specialized queries for PG and sqlite
- hand optimized queries (?)

~~Defining traits for all repos allows us to have multiple implementations for a repo and choose between them at runtime.
Note, for async libs like sqlx we need to use `#[async_trait]` but it seems like graphql already is using it anyway.~~

**Comment by wlthomson** [comment]
The existing static solution was actually chosen over the original trait-based implementation. See b73b8fe8687606be7589d1a3803594b9d9ef8d25 for why we moved away from using dynamic dispatch for this.

My personal 2c on this is that adding dynamic dispatch makes the code a fair bit more complicated (from experience), and that unless there is a strong reason for needing to swap databases at runtime, it would probably be a better use of resources to keep things static and make separate builds for mobile and desktop. Since we are going to need separate binaries for them anyway, and I can't see much use-case for sqlite on desktop, this might be adding complexity to solve a problem that doesn't exist?

**Comment by clemens-msupply** [comment]
Closed: out of scope right now
