### ISSUE TITLE
Split the big repository test into smaller unit tests

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/remote-server#317]
If applicable add:
- tests for foreign key constraint
- upsert

**Comment by wlthomson** [comment]
Not sure what the plan is re. unit tests, but as these tests require a database connection, I would still consider them integration tests and keep them in the `tests` directory. Just my 2c.

**Comment by clemens-msupply** [comment]
I postpone this ticket for a while because its low priority and there are some other things I realized:

- The main reason why I put the tests into integration test was because the tests should run on different backends (at the time there was Mock, Diesel, sqlx) and I wasn't sure where to put these tests in the module. (@chris-morgan is it ok to have test only files in a module, or is that not the Rust way?)
- While we only have Diesel right now IMHO the test should still be running on "generic" repositories and not on a Diesel specific implementation. However, since the whole repo design is a bit in flux right now I think its better to leave the tests where they are for now.

**Comment by chris-morgan** [comment]
You can definitely have test-specific modules. On of the most common patterns for unit tests of crate::alpha::beta is to put them in beta.rs in a `#[cfg(test)] mod tests { … }` block so that their path is crate::alpha::beta::tests::test_\*. But creating a file beta/tests.rs and writing `#[cfg(test)] mod tests;` in beta.rs instead would be perfectly fine too. I would also draw your attention to doc tests, which can be good too (but don’t throw the kitchen sink in there). As far as running the tests on different backends is concerned, #323 should make that smoother.
