### ISSUE TITLE
Remote Sync Spec

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#693]
@clemens-msupply you've mentioned you'll have a look at this, here is some material and thoughts (on top of what's been discussed in our zoom meeting)

Discussion: https://github.com/openmsupply/org-issues/discussions/33

Existing remote sync end point should be here: https://github.com/sussol/msupply/tree/master/Postman

Considerations for existing mSupply: https://github.com/openmsupply/org-issues/discussions/23#discussioncomment-1128211

Should keep incoming sync queue and only integrate records when last record was received: 

Translation Challenges:

* New fields in mSupply, like omsupply_status on transact, and datetimes as text field
* Logic to populate those new fields (existing mSupply -> omSupply)

**Comment by clemens-msupply** [comment]
### Specs for the remote sync queue:

#### Change log table
The change log table records all modification for tables that need to by synced.
The table records which rows have been inserted, updated or deleted (but not what has changed).

```sql
CREATE TABLE changelog (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    -- the table name where the change happend
    table_name TEXT NOT NULL,
    -- row id of the modified row
    row_id TEXT NOT NULL,
    row_action TEXT CHECK (row_action IN ('INSERT', 'UPDATE', 'DELETE')) NOT NULL
)
```
#### Table trigger
Every sync table needs a trigger to record changes to the changelog table:

```sql
CREATE TRIGGER stock_take_insert_trigger
AFTER INSERT
ON stock_take
BEGIN
  INSERT INTO changelog (table_name, row_id, row_action)
    VALUES ('stock_take', new.id, 'INSERT');
END;

CREATE TRIGGER stock_take_update_trigger
AFTER UPDATE
ON stock_take
BEGIN
  INSERT INTO changelog (table_name, row_id, row_action)
    VALUES ('stock_take', new.id, 'UPDATE');
END;

CREATE TRIGGER stock_take_delete_trigger
AFTER DELETE
ON stock_take
BEGIN
  INSERT INTO changelog (table_name, row_id, row_action)
    VALUES ('stock_take', old.id, 'DELETE');
END;
```

#### Out Queue
The outgoing records can be taken straight from the changelog.
Duplicates, e.g. successive updates of a single row should be filtered out:
```sql
SELECT max(id), table_name, row_id, row_action FROM changelog GROUP BY table_name, row_id order by id;
```

#### Remote to central server sync
Records from the out queue are send out to the remote server starting from the lowest changelog id.
The changelog id can be used as a cursor to fetch record in batches.
For every update or insert the current row value is send out.

A problem with this approach is that there is no marker where a DB transaction is finished and the integration on the central server can only happen once all entries in the queue have been received (which implies that the last transaction is finished and the DB is in a consistent state).
(Even if there was a transaction marker, it would be of no use since rows could have been updated in the meantime and old rows from an earlier transaction are not stored, i.e. not all rows might be available to recover an earlier state of the DB.)

Another problem is a "busy" remote server which is constantly adding entries to the change log and the central server can never integrate records because there are always more entries in the queue.
To mitigate this problem the remote server should drain the sync queue in a transaction which allows the remote server to check if the last entry has been handled which can be communicated to the central server which allows the central server to do an integration.
However, if the remote sever is "very busy" and adds items to the change log quicker than sending them out to the remote server the tail of the out queue is never reached in one request and the central server can never integrate the received records.

**Comment by andreievg** [comment]
**Question** How would be stop triggers when re-syncing the site fully (since we will be pulling site owned data, and it shouldn't be resynced back to central) ?

**Note** There will some records that don't actually belong to the site but are required for transfers to be created, for example outbound shipment is sent from remote site, it's used to create inbound shipment for this site, it shouldn't be synced back (similar problem as above).

> SELECT max(id), table_name, row_id, row_action FROM changelog GROUP BY table_name, row_id order by id;

I don't think this query will work, since row_action is not an aggregate and not in group by, also we don't really want to sync a record that was created and deleted (unless the creation was synced already), there is a nice way to aggregate values into array in postgres, this would help. We can probably ignore this for now though, it's an optimisation of sorts (we do have this optimisation in our existing sync btw).

Good to see triggers being 'light'.

> and the integration on the central server can only happen once all entries in the queue have been received

i think it's an ok compromise between space, bandwidth and logical integrity (i know it doesn't guarantee logical integrity of 100%, but i think it would be close). Also this will allow seeing full payload of sync in case there are some integration errors.

> However, if the remote sever is "very busy" and adds items to the change log quicker than sending them out to the remote server the tail of the out queue is never reached in one request and the central server can never integrate the received records.

I think it's a valid theoretical concern, but for some reason I can't quite see it happening in practice, if the site is really that busy, then it should have a pretty good connection to central server or expect integration to only happen at lunch/night (since bandwidth/latency will be the limiting factor). Btw typically in countries we work in bandwidth is pretty good but it's availability isn't, so when there is a connection, it's pretty quick, and I will be surprised if any remote server can be busy enough to keep up with connection speed.

**Comment by clemens-msupply** [comment]
> **Question** How would be stop triggers when re-syncing the site fully (since we will be pulling site owned data, and it shouldn't be resynced back to central) ?

Easiest would be to delete the change log just after doing the initial sync. The remote server wouldn't be allowed to do anything before finishing the first sync, i.e. the very first remote server startup would require connection to the central server.

> 
> **Note** There will some records that don't actually belong to the site but are required for transfers to be created, for example outbound shipment is sent from remote site, it's used to create inbound shipment for this site, it shouldn't be synced back (similar problem as above).

not sure how this is currently handled, maybe do be discussed this afternoon. Naively I would create an inbox outbox like queue on the central server that can be used to communicate between remote servers.

Regarding the query, you mean something like this (sqlite)?
```sql
SELECT max(id), GROUP_CONCAT(row_action) history, table_name, row_id, row_action
	FROM changelog
	GROUP BY table_name, row_id
	HAVING row_action != 'DELETE' OR history NOT LIKE '%INSERT%'
	ORDER BY id
	;
```
If the central server can handle delete messages for rows that don't exist I guess the other query would work as well (assuming quick insert/deletes are rare).

**Comment by Chris-Petty** [comment]
@andreievg @clemens-msupply Couple thoughts:

### Will change log scale on a big site?

We encountered this for postgres/dashboard export. Currently, the `central_change_log` table is used in mSupply for "central" data, but only for tables that are relatively small and stable. `item_store_join` (item visibility) is central data, but can run into the millions of records (e.g. 5000 items, 1000 stores). In this proposed design, it'll instead the store data going into it (all the `xxxx_line` tables), which can easily be orders of magnitude more records than the centrally controlled/system data.

That said, just from sync perspective the `select ... from changelog` command to get the records to sync shouldn't take long even with 10s of millions of records in the change log and only needs to run once per sync cycle/process. The slower bit is almost certainly querying to get the data for each record needed to sync from their respective tables. 

Other things to consider though, like I'm assuming we replace the changelog record every time? Worth benchmarking to make sure that overhead is negligible. 

### Central server inbound queue (`sync_in`?)

I believe there is an inbound record table in omsupply that caches all records coming from the central server before integrating? I have more questions about this but probably for a different channel 😁 .

For here, the implication is that the central server needs a similar mechanism implemented?

### We make bugs; very naughty clients send bad data. How do we handle them?

Just flagging we need to hash out in the protocol how we're handling errors on integration. Should be taken into it's own discussion I reckon but for a hint of my thoughts:

1. Site sends all it's changes, central server keeps them in staging ground/intermediate storage (just going to call `sync_in` for now)
2. Once all received, the server starts integrating the data (Server should track the cursor it successfully gets up to?)
3. The server encounters an issue and can't integrate the data
  1. Does it need to inform the remote site?
  2. Reject further syncs until error is resolved?
  3. ????

### Busy server problem

Valid! As Andrei has said, probably unlikely but in our wildest dreams it'd be a good sign if this happens, it means the omsupply adoption at a big facility is 10/10 😁 . Worth pointing out, this problem would occur the old queuing mechanism too if it was adapted to be "atomic".

For change log, I think the straightforward but perhaps poorly scaling method would be for it to be append only and including the data change in an object field, with marker records indicating cursor points where transactions start and end. The server can safely integrate each data transaction sequentially, even if the remote site is constantly adding them.

Note, at this point I think we'd have gone most of the way to essentially implementing out our WAL 🤣 . Or an event based architecture, same same. If we need the most detailed auditing log possible, it'd be 2 birds with one scone!

Benefit is fixing the atomic problem along with the busy problem. Also just sending field changes will probably reduce bandwidth significantly (citation needed), even if sending multiple updates to the same record. The central server can still likely use one transaction even if multiple are in the queue, but I haven't thought that out much. 

Cons, complexity and overheads associated with it. Also storing all past field changes in log/queue has very, very significant storage requirements. The table is guaranteed to be at least as large as the sum of all the data in regular tables that represent the current state of the system. Totes semantics, but it'd truly be a _log_ containing all _changes_ as the name could be interpreted to mean 😁 .

I'd propose the same if using a queue based sync, the only difference is that we delete the queue record after it's sent/acknowledged, which stops the table (/WAL) becoming gargantuan. (I generally prefer it tbh, especially on central server side)

### Side notes

- The change_log schema is actually pretty much the same as a queue, the only difference is an implementation detail; only updating order the change_log records, rather than deleting them once sent out and acknowledged like you would in a queue.
- Regardless, change log is pretty handy for some integrations mechanisms like this change log likely are pretty handy for integrations that want to subscribe to data in a read only fashion and get a constant feed. Similar to https://docs.couchdb.org/en/stable/api/database/changes.html. That is to say, other systems out there do both change feeds and message queues as different consumers have different needs!

**Comment by clemens-msupply** [comment]
just ran into an issue, in sqlite a REPLACE is a DELETE + INSERT and only triggers an INSERT (not an UPDATE). Do we need to distinguish between insert and update for sync? @Chris-Petty could the central server always do an upsert?

**Comment by Chris-Petty** [comment]
@clemens-msupply yup upsert is fine. The existing v1-v3 central server API actually effectively does this. 
1. It queries to find the record if it already exists. 
2. If it does and the remote site gave "insert" it'll change the action to "update", and vice versa if the record doesn't exist.
