### ISSUE TITLE
Add mock PDF endpoint

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#899]
Add mock PDF endpoint to unblock f/e

**Comment by joshxg** [comment]
@clemens-msupply @andreievg 

The current solution seems confused and brittle to change

Printing documents by themselves is not a report. The current implementation is poorly named (generic reports) and has bad variables (a data id for a report about expiring stock? Reports will need different, more varied variables).

Printing documents is a task which would require internal code changes, where as I could envision a system for reports which did not. So, using enums is a good idea.

Some trivial possible requirement changes: csv instead of pdf, language, multiple documents

Suggest to move closer to something like:

Pseudo

```
enum DocumentType {
    OUTBOUND_SHIPMENT,
    INBOUND_SHIPMENT,
    PICK_SLIP
    RECEIPT
    ...
}

enum FileType {
    PDF,
    CSV
}

type DocumentToFileOptions {
    documentType: DocumentType!
    documentIds: [String!]!
    fileType: FileType
    // More when needed
}

query documentsToFile(storeId: String! input: DocumentToFileOptions)
```

**Comment by clemens-msupply** [comment]
As mentioned the report details will be stored in a report definition which is referred by the report id. The report definition contains all needed information. Note that one requirement is to print reports as a background task without user interaction, e.g. send them out by email,  and you need the full report details for this on the backend... Also see #887.

**Comment by joshxg** [comment]
So then.. a query for report definitions so that the ID can be sent..?

**Comment by clemens-msupply** [comment]
correct, we need an endpoint to query a list of available reports and which data type they are work on

**Comment by clemens-msupply** [comment]
![image](https://user-images.githubusercontent.com/88299195/157558217-a89a5e42-5828-4e83-9cf3-fdbb4e61d89d.png)

@joshxg does this look better to you? you first query a list of available reports and then select one to print. Depending on what context you are in you can filter the report list by category.

**Comment by joshxg** [comment]
Looks great!
