### ISSUE TITLE
No response for shipments / requests ( intermittent )

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#944]
The API on the demo server is at times hanging, and no response is returned to the client.
This is for either shipments or requisitions, and when it happens other queries are returning as normal.
For shipments, removing the `item` node makes the query run normally.

Linked issue: #938 

See also [Josh's comment](https://github.com/openmsupply/openmsupply-client/issues/1055#issuecomment-1068918594) about multiple requests in another issue.

**Comment by andreievg** [comment]
## Replication:

With this branch: https://github.com/openmsupply/remote-server/pull/939
[omsupply-database.sqlite.zip](https://github.com/openmsupply/remote-server/files/8281012/omsupply-database.sqlite.zip)
And data file provided by @joshxg (thanks!!): 

Run first query, then run second query.

Logs don't really help in this case, no response log for invoices query. I debugged:

One breakpoint here (reached 12 times, as expected):
https://github.com/openmsupply/remote-server/blob/4d0d009cf7de5b0080fe5ca9158da64172ebef9d/graphql/types/src/types/invoice_query.rs#L224
One breakpoint here (never reached)
https://github.com/openmsupply/remote-server/blob/4d0d009cf7de5b0080fe5ca9158da64172ebef9d/graphql/types/src/types/invoice_query.rs#L238
One breakpoint here (never reached)
https://github.com/openmsupply/remote-server/blob/4d0d009cf7de5b0080fe5ca9158da64172ebef9d/graphql/core/src/loader/invoice.rs#L59

Looks like pricing loader in first query never go to be resolved due to 'thrown' internal standard graphql error.
And that has broken subsequent loaders from firing, i think I can replicate this in a simple async_graphql setup, but want to try and fix it first, otherwise will make an issue in async_graphql.

<summary>Variables</summary>
<details>
```JSON
{
  "invoiceNumber": 3,
  "first": 20,
  "offset": 0,
  "key": "otherPartyName",
  "desc": false,
  "filter": {
    "type": {
      "equalTo": "INBOUND_SHIPMENT"
    }
  },
  "storeId": "D77F67339BF8400886D009178F4962E1"
}
```
</details

<summary>First Query</summary>
<details>
```gql
query inboundByNumber($invoiceNumber: Int!, $storeId: String!) {
  invoiceByNumber(invoiceNumber: $invoiceNumber, storeId: $storeId, type: INBOUND_SHIPMENT) {
    ... on InvoiceNode {
      ...Inbound
    }
    ... on NodeError {
      __typename
      error {
        description
        ... on RecordNotFound {
          __typename
          description
        }
        ... on DatabaseError {
          __typename
          description
          fullError
        }
      }
    }
  }
}
fragment Inbound on InvoiceNode {
  __typename
  id
  comment
  createdDatetime
  allocatedDatetime
  deliveredDatetime
  pickedDatetime
  shippedDatetime
  verifiedDatetime
  invoiceNumber
  colour
  onHold
  otherPartyId
  otherPartyName
  status
  theirReference
  type
  user {
    __typename
    username
    email
  }
  requisition {
    __typename
    id
    requisitionNumber
    createdDatetime
    user {
      __typename
      username
    }
  }
  lines {
    __typename
    nodes {
      ...InboundLine
    }
    totalCount
  }
  otherParty(storeId: $storeId) {
    __typename
    id
    name
    code
    isCustomer
    isSupplier
  }
  pricing {
    __typename
    totalAfterTax
    totalBeforeTax
    stockTotalBeforeTax
    stockTotalAfterTax
    serviceTotalAfterTax
    serviceTotalBeforeTax
  }
}
fragment InboundLine on InvoiceLineNode {
  __typename
  id
  type
  batch
  costPricePerPack
  sellPricePerPack
  expiryDate
  numberOfPacks
  packSize
  note
  type
  invoiceId
  totalBeforeTax
  totalAfterTax
  item {
    __typename
    id
    name
    code
    unitName
  }
  location {
    __typename
    name
    id
    code
    onHold
  }
  stockLine {
    __typename
    availableNumberOfPacks
    batch
    costPricePerPack
    expiryDate
    id
    itemId
    packSize
    sellPricePerPack
    storeId
    totalNumberOfPacks
    onHold
    note
  }
}

```
</details

<summary>Second Query</summary>
<details>
```gql
query invoices($first: Int, $offset: Int, $key: InvoiceSortFieldInput!, $desc: Boolean, $filter: InvoiceFilterInput, $storeId: String!) {
  invoices(page: {first: $first, offset: $offset}, sort: {key: $key, desc: $desc}, filter: $filter, storeId: $storeId) {
    ... on InvoiceConnector {
      __typename
      totalCount
      nodes {
        ...InboundRow
      }
    }
  }
}
fragment InboundRow on InvoiceNode {
  __typename
  comment
  createdDatetime
  allocatedDatetime
  id
  invoiceNumber
  otherPartyName
  status
  colour
  pricing {
    __typename
    totalAfterTax
  }
}

```
</details>

**Comment by andreievg** [comment]
Tried replacing loader implementation with just  `delay_for(Duration::new(10, 0)).await;`, to see if it's something to do with our loader logic, same issue

**Comment by andreievg** [comment]
I did independent test, managed to replicate it by delay in one loader while another loader errors out, after upgrading to latest async graphql, I can't replicate anymore, so going to upgrade
